language: python

python:
  - 2.7
  - 3.6

install:
  - pip install cython pytest-cov codecov

script:
  - cythonize spector/*.pyx
  - python setup.py build_ext -i
  - pytest -v --cov

after_success:
  - codecov
